name: Build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-pnpm@v1
      - run: pnpm test
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-pnpm@v1
      - name: Release
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
